version: '3'

services:
    demo-api:
        build: .
        ports:
            - 8000:8000
        # env_file:
        #     - ./.env
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - DATABASE=fastapi_app
            - POSTS_TABLE=posts
            - USERS_TABLE=users
            - VOTES_TABLE=votes
            - JWT_SECRET_KEY=super_duper_secret_key
            - JWT_ALOGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        volumes:
            - ./:/usr/src/app:ro # ro=read-only
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        depends_on:
            - postgres

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fastapi_app
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:
