name: Build and deploy code

on: [push, pull_request]

jobs:
    job1:
        runs-on: ubuntu-22.04
        env:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            DATABASE: fastapi_app
            POSTS_TABLE: posts
            USERS_TABLE: users
            VOTES_TABLE: votes
            JWT_SECRET_KEY: super_duper_secret_key
            JWT_ALOGORITHM: HS256
            ACCESS_TOKEN_EXPIRE_MINUTES: 30
        steps:
            - name: Pulling git repo
              uses: actions/checkout@v2
            - name: Installing python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
            - name: Update PIP
              run: python -m pip install -U pip
            - name: Install all dependencies
              run: pip install -r requirements.txt
            - name: Test with pytest
              run: |
                  pip install pytest
                  pip install requests
                  pytest
